import os

from dotenv import load_dotenv

# Tải biến môi trường từ .env
load_dotenv(override=True)

# Facebook Messenger config
SERVER_PORT = int(os.getenv("SERVER_PORT", 8080))
BASE_URL = os.getenv("BASE_URL")
CLIENT_URLS = os.getenv("CLIENT_URLS")
PAGE_ACCESS_TOKEN = os.getenv("PAGE_ACCESS_TOKEN")
VERIFY_TOKEN = os.getenv("VERIFY_TOKEN")
PAGE_ID = os.getenv("PAGE_ID")
DATABASE_URL = os.getenv("DATABASE_URL")
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_SCRIPT_COLLECTION_NAME = os.getenv("QDRANT_SCRIPT_COLLECTION_NAME")
QDRANT_SHEET_COLLECTION_NAME = os.getenv("QDRANT_SHEET_COLLECTION_NAME")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
OLLAMA_API_URL = os.getenv("OLLAMA_API_URL")
OLLAMA_EMBEDDINGS_MODEL = os.getenv("OLLAMA_EMBEDDINGS_MODEL")
OLLAMA_EMBEDDINGS_DIMENSION = int(os.getenv("OLLAMA_EMBEDDINGS_DIMENSION"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
COHERE_API_KEY = os.getenv("COHERE_API_KEY")
AZURE_BLOB_STORAGE_CONNECTION_STRING = os.getenv("AZURE_BLOB_STORAGE_CONNECTION_STRING")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
JINA_API_KEY = os.getenv("JINA_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
