###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################


# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import List, Optional, TypedDict, TypeVar, Union, cast

import baml_py
from typing_extensions import NotRequired

from . import partial_types, types
from .async_request import AsyncHttpRequest, AsyncHttpStreamRequest
from .globals import (
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
    DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
)
from .parser import LlmResponseParser, LlmStreamParser
from .type_builder import TypeBuilder

OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]
    collector: NotRequired[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]]


class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"
    __http_request: "AsyncHttpRequest"
    __http_stream_request: "AsyncHttpStreamRequest"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser
    __baml_options: BamlCallOptions

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager, baml_options: Optional[BamlCallOptions] = None):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager, baml_options)
      self.__http_request = AsyncHttpRequest(self.__runtime, self.__ctx_manager)
      self.__http_stream_request = AsyncHttpStreamRequest(self.__runtime, self.__ctx_manager)
      self.__llm_response_parser = LlmResponseParser(self.__runtime, self.__ctx_manager)
      self.__llm_stream_parser = LlmStreamParser(self.__runtime, self.__ctx_manager)
      self.__baml_options = baml_options or {}

    def with_options(
      self,
      tb: Optional[TypeBuilder] = None,
      client_registry: Optional[baml_py.baml_py.ClientRegistry] = None,
      collector: Optional[Union[baml_py.baml_py.Collector, List[baml_py.baml_py.Collector]]] = None,
    ) -> "BamlAsyncClient":
      """
      Returns a new instance of BamlAsyncClient with explicitly typed baml options
      for Python 3.8 compatibility.
      """
      new_options = self.__baml_options.copy()

      # Override if any keyword arguments were provided.
      if tb is not None:
          new_options["tb"] = tb
      if client_registry is not None:
          new_options["client_registry"] = client_registry
      if collector is not None:
          new_options["collector"] = collector

      return BamlAsyncClient(self.__runtime, self.__ctx_manager, new_options)

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    
    async def MemoryAgent(
        self,
        user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "MemoryAgent",
        {
          "user_prompt": user_prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(str, raw.cast_to(types, types, partial_types, False))
    
    async def MessageRewriteAgent(
        self,
        user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "MessageRewriteAgent",
        {
          "user_prompt": user_prompt,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(str, raw.cast_to(types, types, partial_types, False))
    
    async def ScriptRetrieveAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> types.ScriptRetrieveAgentOutput:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "ScriptRetrieveAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.ScriptRetrieveAgentOutput, raw.cast_to(types, types, partial_types, False))
    
    async def SheetAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> types.SheetAgentOutput:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SheetAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SheetAgentOutput, raw.cast_to(types, types, partial_types, False))
    
    async def SheetGuardAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> types.SheetGuardAgentOutput:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SheetGuardAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SheetGuardAgentOutput, raw.cast_to(types, types, partial_types, False))
    
    async def SheetRAGAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> types.SheetRAGAgentOutput:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SheetRAGAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(types.SheetRAGAgentOutput, raw.cast_to(types, types, partial_types, False))
    
    async def SheetRAGGuardAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> str:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SheetRAGGuardAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(str, raw.cast_to(types, types, partial_types, False))
    
    async def SyntheticAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> List[types.ChatResponseItem]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}

      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = await self.__runtime.call_function(
        "SyntheticAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,"user_prompt": user_prompt,"message_history": message_history,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )
      return cast(List[types.ChatResponseItem], raw.cast_to(types, types, partial_types, False))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __baml_options: BamlCallOptions
    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager, baml_options: Optional[BamlCallOptions] = None):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__baml_options = baml_options or {}

    
    def MemoryAgent(
        self,
        user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[Optional[str], str]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "MemoryAgent",
        {
          "user_prompt": user_prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[Optional[str], str](
        raw,
        lambda x: cast(Optional[str], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(str, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def MessageRewriteAgent(
        self,
        user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[Optional[str], str]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "MessageRewriteAgent",
        {
          "user_prompt": user_prompt,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[Optional[str], str](
        raw,
        lambda x: cast(Optional[str], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(str, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def ScriptRetrieveAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ScriptRetrieveAgentOutput, types.ScriptRetrieveAgentOutput]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "ScriptRetrieveAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.ScriptRetrieveAgentOutput, types.ScriptRetrieveAgentOutput](
        raw,
        lambda x: cast(partial_types.ScriptRetrieveAgentOutput, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.ScriptRetrieveAgentOutput, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SheetAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.SheetAgentOutput, types.SheetAgentOutput]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SheetAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.SheetAgentOutput, types.SheetAgentOutput](
        raw,
        lambda x: cast(partial_types.SheetAgentOutput, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SheetAgentOutput, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SheetGuardAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.SheetGuardAgentOutput, types.SheetGuardAgentOutput]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SheetGuardAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.SheetGuardAgentOutput, types.SheetGuardAgentOutput](
        raw,
        lambda x: cast(partial_types.SheetGuardAgentOutput, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SheetGuardAgentOutput, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SheetRAGAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.SheetRAGAgentOutput, types.SheetRAGAgentOutput]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SheetRAGAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[partial_types.SheetRAGAgentOutput, types.SheetRAGAgentOutput](
        raw,
        lambda x: cast(partial_types.SheetRAGAgentOutput, x.cast_to(types, types, partial_types, True)),
        lambda x: cast(types.SheetRAGAgentOutput, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SheetRAGGuardAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[Optional[str], str]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SheetRAGGuardAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[Optional[str], str](
        raw,
        lambda x: cast(Optional[str], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(str, x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    
    def SyntheticAgent(
        self,
        dynamic_system_prompt: str,user_prompt: str,message_history: List[types.BAMLMessage],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.ChatResponseItem], List[types.ChatResponseItem]]:
      options: BamlCallOptions = {**self.__baml_options, **(baml_options or {})}
      __tb__ = options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = options.get("client_registry", None)
      collector = options.get("collector", None)
      collectors = collector if isinstance(collector, list) else [collector] if collector is not None else []
      raw = self.__runtime.stream_function(
        "SyntheticAgent",
        {
          "dynamic_system_prompt": dynamic_system_prompt,
          "user_prompt": user_prompt,
          "message_history": message_history,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
        collectors,
      )

      return baml_py.BamlStream[List[partial_types.ChatResponseItem], List[types.ChatResponseItem]](
        raw,
        lambda x: cast(List[partial_types.ChatResponseItem], x.cast_to(types, types, partial_types, True)),
        lambda x: cast(List[types.ChatResponseItem], x.cast_to(types, types, partial_types, False)),
        self.__ctx_manager.get(),
      )
    


b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]