###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

from typing import Dict, Generic, List, Literal, TypeVar, Union

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from pydantic import BaseModel

T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class BAMLMessage(BaseModel):
    role: Union[Literal["user"], Literal["assistant"]]
    content: str

class ChatResponseItem(BaseModel):
    type: Union[Literal["text"], Literal["image"], Literal["video"], Literal["audio"], Literal["file"], Literal["link"]]
    payload: str

class GetAllSheetsTool(BaseModel):
    tool_name: Literal["get_all_sheets_tool"]

class GetLocation(BaseModel):
    tool_name: Literal["get_location"]

class GetTimezone(BaseModel):
    tool_name: Literal["get_timezone"]
    city: str

class OutputTool(BaseModel):
    tool_name: Literal["output_tool"]
    message_parts: List["ChatResponseItem"]

class SQLQueryTool(BaseModel):
    tool_name: Literal["sql_query_tool"]
    query: str

class ScriptRetrieveAgentOutput(BaseModel):
    should_query_sheet: bool
    pieces_of_information: List[str]

class SheetAgentOutput(BaseModel):
    sql_query: str
    sheet_id: str
    limit: int

class SheetGuardAgentOutput(BaseModel):
    should_query_sheet: bool
